version: '3.8'
services:
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./urls.txt:/app/urls.txt      # put your list of URLs here
    command: ["--file", "urls.txt"]
